# Generated by Django 2.0.1 on 2018-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
