# Generated by Django 2.0.1 on 2018-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20180318_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='theatre_name',
            field=models.CharField(default='theatre', max_length=100),
        ),
    ]
