# Generated by Django 2.0.1 on 2018-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20180321_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('theatre_name', models.CharField(max_length=200)),
            ],
        ),
    ]
